name: Example Workflow
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Permissions
        uses: ./
        with:
          permissions-file: 'permissions.yml'

      - name: Echo Something
        run: echo "Hello World!"
